### PR TITLE
Fix/compilable 1.11.2

### PR DESCRIPTION
**Pull request by ghost**
Made compileable. Dragon can be ridden.

Breeding hasn't been tested yet.

### CODE REVIEW

**Comment by ata4** [comment]
Thanks, I have given up a bit last time I've tried to port it. I think I was fighting with outdated source archives and just couldn't figure out what's wrong.

**Comment by JonL98** [comment]
Here's a crash I got when I actually loaded the mod in Minecraft. Something goes wrong at "onPreInit" in the ClientProxy, CommonProxy, and DragonMounts classes.
https://pastebin.com/jFvAGJcK

**Comment by ghost** [comment]
Have checked the code around the crash at GameData.BlockCallbacks.onAdd . Seems that BlockDragonBreedEgg.getStateFromMeta(int) returns a value more than 15, which would lead to such crash. This is strange because EnumDragonBreed contains only entries from 0 - 7 . Have this enum been modified?

**Comment by JonL98** [comment]
Yeah, I have more than 8 on my branch, but ata's branch shouldn't. I'll take a look at that BlockDragonBreedEgg class then.

**Comment by JonL98** [comment]
So are you saying that somewhere in the mod there's still a limiting value for number of breeds aside from EnumDragonBreed?

**Comment by ghost** [comment]
Not directly in the mod. But Forge has introduced this limitation for any Block.getStateFromMeta(int) overrides.

I'm new to 1.11 modding as I previously developed for 1.7.10. But from what I've seen I would guess, that the meta values are replaced by block state properties and should be used instead.

**Comment by ghost** [comment]
http://www.minecraftforge.net/forum/topic/44674-1102-help-with-getstatefrommetagetmetafromstate/ is also addressing a similar issue.

Maybe registering multiple DragonEgg block types with different enums would also help.

**Comment by JonL98** [comment]
Urgh, that sounds like work. In the meantime, I'll just take a couple breeds out. I'll run it through 1.12 forge too and get an idea of what has to happen for the next version.

**Pull request merged**
