### PR TITLE
Breathweapon

### PR DESCRIPTION
**Pull request by TheGreyGhost**
In this branch I've added the breath weapon back.  
I also added a dragon orb - when you point the orb at a target object (creature, block, or a direction) your tamed dragon will move towards the target and breathe fire at the target when it is in range.

The fire weapon will affect any blocks or entities it collides with-
1) after short exposure, will set fire to flammable objects
2) will burn grass to dirt
3) after longer exposure, will smelt blocks (eg sand -> glass)
4) after even longer exposure, will turn non-smeltable blocks into lava

The code is designed so that different effects can be added for different breath weapons (for example - ice shards for ice dragon; strong wind gusts for aether dragon etc).  Haven't added these yet!

In the next few days I will put some documentation together on the class structure of the new breath weapon code I added.

I've tested the code on multiplayer and also on dedicated server, it seems to work ok.

A couple of strange things still - eg when the dragon lands in water it gets confused - but no serious glitches that I found yet.

The next things I was thinking of working on- in no particular order-
- different breath types
- making the dragon semi-transparent so you can aim more easily while riding him
- fixing the land-in-water problem
- adding AI for the dragon to fly around without a rider.

### CODE REVIEW

**Comment by SupernovaCo** [comment]
Quick suggestion: Aether dragon lightning breathweapon?

**Comment by Spartan322** [comment]
Also, might want to squash those commits a bit.

**Comment by ata4** [comment]
Well, I'll be damned, that's a lot of commits! And it appears to be in conflict with the main branch. I think I may have to pull that into a testing branch first and go through all that code before putting that into main. I also have to make sure it's not stressing the server too much, I'm curious how you solved that problem.

**Comment by TheGreyGhost** [comment]
Hi
Yeah it is a lot of commits, should have squashed first, sorry.
One of the last things I did was to merge from the main branch of your master, so hopefully there are no major conflicts, but it didn't go 100% smoothly and I think you've made a couple more commits since then, which might be the reason for the conflict you saw.

There isn't much communication between the client and the server.  
Client sends the current target (eg entityID) to the server, which keeps track of all players' targets and sends them to other clients (via DataWatcher on the corresponding dragon entity) when the dragon starts breathing.  That's the only network traffic related to the breath weapon, i.e. ranging from ten bytes per second to a few hundred bytes per second.

The spawning of EntityFX on the client is done locally based on the DataWatcher target.
The collision calculations between the breath weapon and nearby blocks+entities are done by the server and the results (damage etc) are synchronised to the clients by vanilla; but there is no Entity or EntityFX information exchanged between the two.  The collision calculations themselves have a couple of basic optimisations to speed them up and in my profiling tests they took negligible time - but my machine is pretty quick so doing those tests on your side is probably a good idea!

Briefly how it works:
On client:
DragonOrbControl monitors user input and sends a DragonTargetMessage to the server when the player's target has changed.

On server:
Receives DragonTargetMessage, caches the corresponding BreathWeaponTarget locally (in  DragonOrbTargets)  
DragonBreathHelper then uses AI to move the dragon to an appropriate range and to start breathing when ready - the breathing target is sent to nearby clients using a DataWatcher on the dragon. 

Back on client:
DragonBreathHelper for each each dragon retrieves the current target from the DataWatcher, then spawns the breath using
BreathWeaponEmitter, which creates a stream of FlameBreathFX for rendering & collision, each with a corresponding BreathNode to model the size, aging, power etc of each FlameBreathFX.

Meanwhile on the server, the effects of the breath weapon are modelled by creating a stream of EntityBreathNodes with corresponding BreathNodes, similar to the client.  (The EntityBreathNodes are not spawned, just stored in a collection).  Collision detection is performed between the EntityBreathNodes and the blocks and nearby entities - once a block or entity has suffered enough collisions with nodes, it takes damage / gets smelted / etc.
The main classes modelling this are DragonBreathHelper, BreathWeapon, BreathNode, EntityBreathNode, BreathAffectedBlock/Entity
The collision detection is in BreathAffectedArea and NodeLineSegment.

Adding new types of breath is intended to be done by overriding 
BreathWeapon, 
BreathWeaponEmitter, with different equivalents for FlameBreathFX.
BreathNode
but not all the classes implement this fully yet (for example, BreathAffectedArea will need to use BreathWeapon to spawn BreathNodes with the correct speed and size; BreathNode is currently hard-coded values).

Pretty much all the other changes to the code are related to making sure the breath weapon nodes spawn from the dragon's mouth - which is affected by yaw and pitch and size etc - so I moved the positioning code into a common class for both server and client.  That was pretty fiddly to get right.

Oh and I changed from a config file to a config screen - should have put that in a separate branch, sorry about that, didn't think of it until later.

-TGG

**Comment by ata4** [comment]
You changed the code formatting in some existing classes, I think that's one of the reasons why there are conflicts now. But it can be fixed easily.

**Comment by ata4** [comment]
Okay, I did some initial testing and I must say... I'm impressed. Good job! :+1:

Can you please also generate a short list of the most relevant changes for the changelog?

**Comment by TheGreyGhost** [comment]
Thanks :)  It was good fun that's for sure.

Changelog:
1) Gave all dragons the ability to breathe fire
2) Added a "dragon orb" item- a player can point the orb at a target and his/her tame dragons will breathe at it.  (Crafting recipe is an ender eye on top two blaze rods - similar shape to crafting a shovel)
3) Implemented configuration GUI 

Is that what you need?

Cheers
  TGG

**Comment by ata4** [comment]
Yep, pretty much, but I think there are more changes for the AI. Or are these for the orb only?

**Comment by TheGreyGhost** [comment]
I just had a look at the diff and you're right, there are a few minor tweaks to some of the AI,  they are all refactorings without symptoms except for
- a couple of new AI related to the orb, plus
-minor change to altitude control when riding the dragon - the dragon altitude is now controlled only by the R and F keys, not by where the player is looking.  (The player look only affects yaw).  I did this because my dragon kept crashing into the ground when I was using the orb while flying...

**Comment by TheGreyGhost** [comment]
Hi 
Just a question - do you have a timeline for merging this branch?  I'd like to continue with the other breath types, but I'd prefer to fork it from your merge rather than mine. 

Also, do you plan to release it?  If not, would you mind if I post it separately as an "extension" of yours?

Cheers
  TGG

**Comment by ata4** [comment]
I'm not yet sure if it's ready to be merged into main. I've yet have to do some testing on dedicated servers to make sure it's working there, too. I planned to release it as a side built for testing first, but since you want to continue working on it, I'll merge it now.

**Comment by TheGreyGhost** [comment]
keen, thanks!

-TGG

**Pull request merged**
